version: "3"

services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
    online-shop:
        container_name: online-shop
        image: olshop:1.0
        ports: 
            - "8000:${PORT}"
        links: 
            - mongo
        depends_on: 
            - mongo